.PHONY: vpc eks-cluster core

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

vpc:
	echo

eks-cluster:
	echo 

core: vpc eks-cluster

masterdata:
	echo 

io:
	echo 

enterprise:
	echo 